include("${CMAKE_CURRENT_LIST_DIR}/NowideTargets.cmake")

# Populate missing release configurations
cmake_policy(PUSH)
cmake_policy(SET CMP0057 NEW)
if("RelWithDebInfo" IN_LIST IMPORTED_CONFIGURATIONS)
  if(NOT "Release" IN_LIST IMPORTED_CONFIGURATIONS)
    set_target_properties(Nowide::nowide-static PROPERTIES MAP_IMPORTED_CONFIG_RELEASE RelWithDebInfo)
    set_target_properties(Nowide::nowide PROPERTIES MAP_IMPORTED_CONFIG_RELEASE RelWithDebInfo)
  endif()
  if(NOT "MinSizeRel" IN_LIST IMPORTED_CONFIGURATIONS)
    set_target_properties(Nowide::nowide-static PROPERTIES MAP_IMPORTED_CONFIG_MINSIZEREL RelWithDebInfo)
    set_target_properties(Nowide::nowide PROPERTIES MAP_IMPORTED_CONFIG_MINSIZEREL RelWithDebInfo)
  endif()
elseif("Release" IN_LIST IMPORTED_CONFIGURATIONS)
  set_target_properties(Nowide::nowide-static PROPERTIES MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release)
  set_target_properties(Nowide::nowide PROPERTIES MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release)
  if(NOT "MinSizeRel" IN_LIST IMPORTED_CONFIGURATIONS)
    set_target_properties(Nowide::nowide-static PROPERTIES MAP_IMPORTED_CONFIG_MINSIZEREL Release)
    set_target_properties(Nowide::nowide PROPERTIES MAP_IMPORTED_CONFIG_MINSIZEREL Release)
  endif()
elseif("MinSizeRel" IN_LIST IMPORTED_CONFIGURATIONS)
  set_target_properties(Nowide::nowide-static PROPERTIES MAP_IMPORTED_CONFIG_RELWITHDEBINFO MinSizeRel)
  set_target_properties(Nowide::nowide PROPERTIES MAP_IMPORTED_CONFIG_RELWITHDEBINFO MinSizeRel)
  set_target_properties(Nowide::nowide-static PROPERTIES MAP_IMPORTED_CONFIG_RELEASE MinSizeRel)
  set_target_properties(Nowide::nowide PROPERTIES MAP_IMPORTED_CONFIG_RELEASE MinSizeRel)
endif()
cmake_policy(POP)
